spring:
  datasource:
    url: jdbc:mysql://localhost:3306/file_record?serverTimezone=Asia/Shanghai&characterEncoding=utf8&useSSL=false
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: com.mysql.jdbc.Driver
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB
mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
aliyun:
  oss:
    endpoint: http://oss-cn-beijing.aliyuncs.com
    accessKeyId: ${ALIYUN_OSS_ACCESS_KEY_ID}
    accessKeySecret: ${ALIYUN_OSS_ACCESS_KEY_SECRET}
    bucketName: fileuploadcoderqi


